import { useMemo, useState } from "react";
import { Link, NavLink, useLocation } from "react-router-dom";
import { BarChart3, BedDouble, Bell, CalendarDays, ChevronRight, CircleDollarSign, ClipboardList, Coffee, FileText, Image as ImageIcon, LayoutDashboard, LogOut, Menu, MessageSquare, Percent, Search, Settings, Star, Users, Utensils, X } from "lucide-react";

const nav=[
["/admin","Overview",LayoutDashboard],["/admin/bookings","Bookings",ClipboardList],["/admin/rooms","Rooms",BedDouble],
["/admin/customers","Customers",Users],["/admin/restaurant","Restaurant",Utensils],["/admin/room-service","Room Service",Coffee],
["/admin/reviews","Reviews",Star],["/admin/gallery","Gallery",ImageIcon],["/admin/coupons","Coupons",Percent],
["/admin/events","Events",CalendarDays],["/admin/messages","Messages",MessageSquare],["/admin/analytics","Analytics",BarChart3],["/admin/settings","Settings",Settings],
] as const;
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
type Booking={id:string;guest:string;room:string;checkIn:string;checkOut:string;amount:number;status:string;payment:string};
const bookings:Booking[]=[
{ id:"GC-1028",guest:"Aarav Sharma",room:"Courtyard Deluxe",checkIn:"26 Sep 2026",checkOut:"28 Sep 2026",amount:8400,status:"Confirmed",payment:"Paid"},
{ id:"GC-1027",guest:"Priya Singh",room:"Grand Suite",checkIn:"27 Sep 2026",checkOut:"30 Sep 2026",amount:14112,status:"Confirmed",payment:"Paid"},
{ id:"GC-1026",guest:"Rahul Kumar",room:"Executive King",checkIn:"26 Sep 2026",checkOut:"27 Sep 2026",amount:5040,status:"Checked in",payment:"Paid"},
{ id:"GC-1025",guest:"Neha Verma",room:"Courtyard Deluxe",checkIn:"29 Sep 2026",checkOut:"01 Oct 2026",amount:8400,status:"Pending",payment:"Pending"},
{ id:"GC-1024",guest:"Vikash Gupta",room:"Executive King",checkIn:"24 Sep 2026",checkOut:"26 Sep 2026",amount:5040,status:"Checked out",payment:"Paid"}];
const rooms=[["Courtyard Deluxe","Deluxe","₹3,750","Available"],["Grand Suite","Suite","₹6,300","Available"],["Executive King","Executive","₹4,500","Maintenance"],["Garden Twin","Twin","₹3,200","Available"],["Premium Suite","Suite","₹7,100","Inactive"],["Family Courtyard","Family","₹5,200","Available"]];

function Status({children}:{children:string}){return <span className="badge">{children}</span>}
function Metric({label,value,change,icon:Icon}:{label:string;value:string;change:string;icon:typeof BarChart3}){return <div className="rounded-[24px] border border-black/5 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><div className="text-sm text-ink/45">{label}</div><div className="mt-2 text-2xl font-semibold text-forest">{value}</div><div className="mt-2 text-xs text-ink/45">{change}</div></div><div className="rounded-2xl bg-cream p-3 text-gold"><Icon size={19}/></div></div></div>}

function Sidebar({open,onClose}:{open:boolean;onClose:()=>void}){return <><aside className={(open?"translate-x-0":"-translate-x-full")+" fixed inset-y-0 left-0 z-[60] w-[270px] border-r border-black/5 bg-[#fbf7ef] p-5 transition-transform lg:static lg:z-auto lg:translate-x-0"}><div className="flex items-center justify-between"><Link to="/admin" onClick={onClose}><div className="eyebrow">Administration</div><div className="mt-1 font-serif text-2xl text-forest">Grand Courtyard</div></Link><button className="p-2 lg:hidden" onClick={onClose}><X size={19}/></button></div><div className="mt-8 rounded-2xl bg-forest p-4 text-white"><div className="text-xs text-white/55">Current workspace</div><div className="mt-1 font-semibold">Hotel Operations</div><div className="mt-1 text-xs text-white/55">Demo mode · Firebase later</div></div><nav className="mt-6 space-y-1">{nav.map(([path,label,Icon])=><NavLink key={path} to={path} end={path==="/admin"} onClick={onClose} className={({isActive})=>"flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm "+(isActive?"bg-white font-semibold text-forest shadow-sm":"text-ink/55 hover:bg-white/70")}><Icon size={17}/><span>{label}</span></NavLink>)}</nav><Link to="/" className="mt-6 flex items-center gap-3 px-3 py-2.5 text-sm text-ink/50"><LogOut size={17}/> Back to website</Link></aside>{open&&<button className="fixed inset-0 z-50 bg-black/30 lg:hidden" onClick={onClose}/>}</>}

function Shell({children}:{children:React.ReactNode}){const [open,setOpen]=useState(false);return <div className="min-h-screen bg-[#f6f2e9] lg:flex"><Sidebar open={open} onClose={()=>setOpen(false)}/><div className="min-w-0 flex-1"><header className="sticky top-0 z-40 border-b border-black/5 bg-[#f6f2e9]/90 backdrop-blur"><div className="flex h-[74px] items-center justify-between px-5 sm:px-8"><button className="rounded-xl border bg-white p-2.5 lg:hidden" onClick={()=>setOpen(true)}><Menu size={19}/></button><div className="hidden max-w-md flex-1 items-center gap-3 rounded-xl border bg-white px-3 sm:flex"><Search size={17} className="text-ink/35"/><input className="w-full bg-transparent py-2 text-sm outline-none" placeholder="Search bookings, guests, rooms..."/></div><div className="ml-auto flex items-center gap-3"><button className="rounded-xl border bg-white p-2.5"><Bell size={18}/></button><div className="flex items-center gap-3 rounded-xl border bg-white px-3 py-2"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-forest text-xs font-bold text-white">GC</div><div className="hidden sm:block"><div className="text-sm font-semibold text-forest">Hotel Admin</div><div className="text-[11px] text-ink/40">Administrator</div></div></div></div></div></header><main className="p-5 sm:p-8">{children}</main></div></div>}

function Head({eyebrow,title,body,action}:{eyebrow:string;title:string;body:string;action?:React.ReactNode}){return <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="eyebrow">{eyebrow}</div><h1 className="section-title mt-2 text-forest">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-ink/55">{body}</p></div>{action}</div>}

function Overview(){return <><Head eyebrow="Saturday · 26 September 2026" title="Good afternoon." body="Here is what is happening across The Grand Courtyard today." action={<Link className="btn-primary" to="/admin/bookings">Manage bookings <ChevronRight size={16}/></Link>}/><div className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900"><strong>Demo mode:</strong> sample operational data is shown until Firebase is connected.</div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Today's revenue" value={money(53460)} change="+12.4% vs previous day" icon={CircleDollarSign}/><Metric label="Bookings" value="28" change="6 arrivals · 4 departures" icon={CalendarDays}/><Metric label="Occupancy" value="76%" change="19 of 25 rooms occupied" icon={BedDouble}/><Metric label="Guests" value="42" change="8 new guests today" icon={Users}/></div><div className="mt-6 rounded-[26px] border border-black/5 bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-forest">Recent bookings</h2><p className="mt-1 text-xs text-ink/40">Latest reservation activity</p></div><Link className="text-sm font-semibold text-forest" to="/admin/bookings">View all</Link></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-black/5 text-xs text-ink/40"><tr><th className="pb-3">Booking</th><th className="pb-3">Guest</th><th className="pb-3">Room</th><th className="pb-3">Amount</th><th className="pb-3">Status</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id} className="border-b border-black/5 last:border-0"><td className="py-4 font-semibold text-forest">{b.id}</td><td className="py-4">{b.guest}</td><td className="py-4 text-ink/55">{b.room}</td><td className="py-4">{money(b.amount)}</td><td className="py-4"><Status>{b.status}</Status></td></tr>)}</tbody></table></div></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><Link to="/admin/rooms" className="rounded-2xl border border-black/5 bg-white p-5"><BedDouble className="text-gold"/><div className="mt-4 font-semibold text-forest">Room operations</div><div className="mt-1 text-sm text-ink/50">1 room needs attention</div></Link><Link to="/admin/reviews" className="rounded-2xl border border-black/5 bg-white p-5"><Star className="text-gold"/><div className="mt-4 font-semibold text-forest">Review moderation</div><div className="mt-1 text-sm text-ink/50">5 reviews awaiting review</div></Link><Link to="/admin/messages" className="rounded-2xl border border-black/5 bg-white p-5"><MessageSquare className="text-gold"/><div className="mt-4 font-semibold text-forest">Guest messages</div><div className="mt-1 text-sm text-ink/50">7 unread enquiries</div></Link></div></>}

function Bookings(){const [filter,setFilter]=useState("All"),[q,setQ]=useState("");const filtered=useMemo(()=>bookings.filter(b=>(filter==="All"||b.status===filter)&&[b.id,b.guest,b.room].join(" ").toLowerCase().includes(q.toLowerCase())),[filter,q]);return <><Head eyebrow="Reservations" title="Booking management" body="Monitor arrivals, departures, payment status and reservation state." action={<button className="btn-primary">New booking</button>}/><div className="mt-6 flex flex-col gap-3 rounded-[24px] border border-black/5 bg-white p-4 md:flex-row"><div className="flex flex-1 items-center gap-3 rounded-xl border border-black/10 px-3"><Search size={17} className="text-ink/35"/><input className="w-full bg-transparent py-2 outline-none" placeholder="Search booking, guest or room" value={q} onChange={e=>setQ(e.target.value)}/></div><select className="input md:w-44" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Confirmed</option><option>Pending</option><option>Checked in</option><option>Checked out</option><option>Cancelled</option></select></div><div className="mt-5 overflow-x-auto rounded-[26px] border border-black/5 bg-white"><table className="w-full min-w-[950px] text-left text-sm"><thead className="border-b border-black/5 text-xs text-ink/40"><tr>{["Booking","Guest","Room","Stay","Amount","Payment","Status",""].map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody>{filtered.map(b=><tr key={b.id} className="border-b border-black/5 last:border-0"><td className="px-5 py-4 font-semibold text-forest">{b.id}</td><td className="px-5 py-4">{b.guest}</td><td className="px-5 py-4 text-ink/55">{b.room}</td><td className="px-5 py-4 text-xs text-ink/55">{b.checkIn}<br/>→ {b.checkOut}</td><td className="px-5 py-4 font-semibold">{money(b.amount)}</td><td className="px-5 py-4"><Status>{b.payment}</Status></td><td className="px-5 py-4"><Status>{b.status}</Status></td><td className="px-5 py-4"><button className="text-sm font-semibold text-forest">View</button></td></tr>)}</tbody></table></div></>}

function Rooms(){const [q,setQ]=useState("");const filtered=rooms.filter(r=>r[0].toLowerCase().includes(q.toLowerCase()));return <><Head eyebrow="Inventory" title="Rooms" body="Manage room types, pricing, availability and featured inventory." action={<button className="btn-primary">Add room</button>}/><div className="mt-6 flex items-center gap-3 rounded-xl border border-black/10 bg-white px-3 sm:max-w-sm"><Search size={17} className="text-ink/35"/><input className="w-full bg-transparent py-3 outline-none" placeholder="Search rooms" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(r=><div className="overflow-hidden rounded-[26px] border border-black/5 bg-white" key={r[0]}><div className="h-32 bg-gradient-to-br from-[#e9dfcc] to-[#cbb995]"/><div className="p-5"><div className="flex justify-between gap-4"><div><div className="font-semibold text-forest">{r[0]}</div><div className="mt-1 text-xs text-ink/45">{r[1]} · 2–3 guests</div></div><Status>{r[3]}</Status></div><div className="mt-5 flex items-end justify-between"><div><div className="text-2xl font-semibold text-forest">{r[2]}</div><div className="text-xs text-ink/40">per night</div></div><button className="btn-secondary min-h-9 px-3 text-xs">Edit</button></div></div></div>)}</div></>}

function Generic({title,eyebrow,icon:Icon,body,items}:{title:string;eyebrow:string;icon:typeof FileText;body:string;items:string[]}){return <><Head eyebrow={eyebrow} title={title} body={body} action={<button className="btn-primary">Add new</button>}/><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((x,i)=><div className="rounded-[24px] border border-black/5 bg-white p-6" key={x}><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-cream text-gold"><Icon size={19}/></div><div className="mt-5 font-semibold text-forest">{x}</div><p className="mt-2 text-sm leading-6 text-ink/50">{i%2?"Manage status, details and operational records.":"Review content and keep this section ready for Firebase data."}</p><button className="mt-5 text-sm font-semibold text-forest">Open section →</button></div>)}</div></>}

function Analytics(){return <><Head eyebrow="Insights" title="Analytics" body="Track revenue, occupancy and booking performance."/><div className="mt-6 grid gap-5 lg:grid-cols-3"><Metric label="Monthly revenue" value="₹8.42L" change="+8.7% month over month" icon={CircleDollarSign}/><Metric label="Average occupancy" value="71%" change="Last 30 days" icon={BarChart3}/><Metric label="Average booking value" value="₹6,980" change="Across 121 bookings" icon={FileText}/></div><div className="mt-6 rounded-[26px] border border-black/5 bg-white p-6"><div className="font-semibold text-forest">Revenue trend</div><div className="mt-6 flex h-56 items-end gap-3">{[35,48,42,65,58,72,68,82,76,91,85,96].map((h,i)=><div key={i} className="flex-1 rounded-t-xl bg-forest/80" style={{height:h+"%"}} title={"Month "+(i+1)}/>)}</div></div></>}

export default function AdminDashboard(){const {pathname}=useLocation();let content:React.ReactNode;if(pathname==="/admin")content=<Overview/>;else if(pathname==="/admin/bookings")content=<Bookings/>;else if(pathname==="/admin/rooms")content=<Rooms/>;else if(pathname==="/admin/analytics")content=<Analytics/>;else if(pathname==="/admin/customers")content=<Generic title="Customers" eyebrow="Guests" icon={Users} body="Customer records and stay history." items={["Guest directory","Repeat guests","Guest profiles"]}/>;else if(pathname==="/admin/restaurant")content=<Generic title="Restaurant" eyebrow="Dining" icon={Utensils} body="Manage menu items and availability." items={["Menu items","Categories","Dining settings"]}/>;else if(pathname==="/admin/room-service")content=<Generic title="Room service" eyebrow="In-room dining" icon={Coffee} body="Track room-service orders." items={["Active orders","Order history","Service settings"]}/>;else if(pathname==="/admin/reviews")content=<Generic title="Reviews" eyebrow="Guest feedback" icon={Star} body="Moderate guest reviews." items={["Pending reviews","Approved reviews","Rejected reviews"]}/>;else if(pathname==="/admin/gallery")content=<Generic title="Gallery" eyebrow="Hotel media" icon={ImageIcon} body="Manage hotel photography." items={["Hotel photos","Room photos","Restaurant photos"]}/>;else if(pathname==="/admin/coupons")content=<Generic title="Coupons" eyebrow="Promotions" icon={Percent} body="Create and monitor promotional codes." items={["Active coupons","Expired coupons","Usage reports"]}/>;else if(pathname==="/admin/events")content=<Generic title="Events" eyebrow="Meetings & celebrations" icon={CalendarDays} body="Manage event enquiries." items={["New enquiries","Upcoming events","Event spaces"]}/>;else if(pathname==="/admin/messages")content=<Generic title="Messages" eyebrow="Guest communication" icon={MessageSquare} body="Review contact messages." items={["Unread messages","All enquiries","Resolved messages"]}/>;else content=<Generic title="Settings" eyebrow="Configuration" icon={Settings} body="Hotel profile, policies and operational settings." items={["Hotel profile","Booking policies","Payment settings","Notifications","Staff access","Audit log"]}/>;return <Shell>{content}</Shell>}
