import { useMemo, useState } from "react";
import { Link, NavLink, useLocation } from "react-router-dom";
import { BarChart3, BedDouble, Bell, CalendarDays, ChevronRight, CircleDollarSign, ClipboardList, Coffee, FileText, Image as ImageIcon, LayoutDashboard, LogOut, Menu, MessageSquare, Percent, Search, Settings, Star, Users, Utensils, X } from "lucide-react";

const nav=[
["/admin","Overview",LayoutDashboard],["/admin/bookings","Bookings",ClipboardList],["/admin/rooms","Rooms",BedDouble],
["/admin/customers","Customers",Users],["/admin/restaurant","Restaurant",Utensils],["/admin/room-service","Room Service",Coffee],
["/admin/reviews","Reviews",Star],["/admin/gallery","Gallery",ImageIcon],["/admin/coupons","Coupons",Percent],
["/admin/events","Events",CalendarDays],["/admin/messages","Messages",MessageSquare],["/admin/analytics","Analytics",BarChart3],["/admin/settings","Settings",Settings],
] as const;
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
type Booking={id:string;guest:string;room:string;checkIn:string;checkOut:string;amount:number;status:string;payment:string};
const bookings:Booking[]=[
{ id:"GC-1028",guest:"Aarav Sharma",room:"Courtyard Deluxe",checkIn:"26 Sep 2026",checkOut:"28 Sep 2026",amount:8400,status:"Confirmed",payment:"Paid"},
{ id:"GC-1027",guest:"Priya Singh",room:"Grand Suite",checkIn:"27 Sep 2026",checkOut:"30 Sep 2026",amount:14112,status:"Confirmed",payment:"Paid"},
{ id:"GC-1026",guest:"Rahul Kumar",room:"Executive King",checkIn:"26 Sep 2026",checkOut:"27 Sep 2026",amount:5040,status:"Checked in",payment:"Paid"},
{ id:"GC-1025",guest:"Neha Verma",room:"Courtyard Deluxe",checkIn:"29 Sep 2026",checkOut:"01 Oct 2026",amount:8400,status:"Pending",payment:"Pending"},
{ id:"GC-1024",guest:"Vikash Gupta",room:"Executive King",checkIn:"24 Sep 2026",checkOut:"26 Sep 2026",amount:5040,status:"Checked out",payment:"Paid"}];
const rooms=[["Courtyard Deluxe","Deluxe","₹3,750","Available"],["Grand Suite","Suite","₹6,300","Available"],["Executive King","Executive","₹4,500","Maintenance"],["Garden Twin","Twin","₹3,200","Available"],["Premium Suite","Suite","₹7,100","Inactive"],["Family Courtyard","Family","₹5,200","Available"]];

function Status({children}:{children:string}){return <span className="badge">{children}</span>}
function Metric({label,value,change,icon:Icon}:{label:string;value:string;change:string;icon:typeof BarChart3}){return <div className="rounded-[24px] border border-black/5 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><div className="text-sm text-ink/45">{label}</div><div className="mt-2 text-2xl font-semibold text-forest">{value}</div><div className="mt-2 text-xs text-ink/45">{change}</div></div><div className="rounded-2xl bg-cream p-3 text-gold"><Icon size={19}/></div></div></div>}

function Sidebar({open,onClose}:{open:boolean;onClose:()=>void}){return <><aside className={(open?"translate-x-0":"-translate-x-full")+" fixed inset-y-0 left-0 z-[60] w-[270px] border-r border-black/5 bg-[#fbf7ef] p-5 transition-transform lg:static lg:z-auto lg:translate-x-0"}><div className="flex items-center justify-between"><Link to="/admin" onClick={onClose}><div className="eyebrow">Administration</div><div className="mt-1 font-serif text-2xl text-forest">Grand Courtyard</div></Link><button className="p-2 lg:hidden" onClick={onClose}><X size={19}/></button></div><div className="mt-8 rounded-2xl bg-forest p-4 text-white"><div className="text-xs text-white/55">Current workspace</div><div className="mt-1 font-semibold">Hotel Operations</div><div className="mt-1 text-xs text-white/55">Demo mode · Firebase later</div></div><nav className="mt-6 space-y-1">{nav.map(([path,label,Icon])=><NavLink key={path} to={path} end={path==="/admin"} onClick={onClose} className={({isActive})=>"flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm "+(isActive?"bg-white font-semibold text-forest shadow-sm":"text-ink/55 hover:bg-white/70")}><Icon size={17}/><span>{label}</span></NavLink>)}</nav><Link to="/" className="mt-6 flex items-center gap-3 px-3 py-2.5 text-sm text-ink/50"><LogOut size={17}/> Back to website</Link></aside>{open&&<button className="fixed inset-0 z-50 bg-black/30 lg:hidden" onClick={onClose}/>}</>}

function Shell({children}:{children:React.ReactNode}){const [open,setOpen]=useState(false);return <div className="min-h-screen bg-[#f6f2e9] lg:flex"><Sidebar open={open} onClose={()=>setOpen(false)}/><div className="min-w-0 flex-1"><header className="sticky top-0 z-40 border-b border-black/5 bg-[#f6f2e9]/90 backdrop-blur"><div className="flex h-[74px] items-center justify-between px-5 sm:px-8"><button className="rounded-xl border bg-white p-2.5 lg:hidden" onClick={()=>setOpen(true)}><Menu size={19}/></button><div className="hidden max-w-md flex-1 items-center gap-3 rounded-xl border bg-white px-3 sm:flex"><Search size={17} className="text-ink/35"/><input className="w-full bg-transparent py-2 text-sm outline-none" placeholder="Search bookings, guests, rooms..."/></div><div className="ml-auto flex items-center gap-3"><button className="rounded-xl border bg-white p-2.5"><Bell size={18}/></button><div className="flex items-center gap-3 rounded-xl border bg-white px-3 py-2"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-forest text-xs font-bold text-white">GC</div><div className="hidden sm:block"><div className="text-sm font-semibold text-forest">Hotel Admin</div><div className="text-[11px] text-ink/40">Administrator</div></div></div></div></div></header><main className="p-5 sm:p-8">{children}</main></div></div>}

function Head({eyebrow,title,body,action}:{eyebrow:string;title:string;body:string;action?:React.ReactNode}){return <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="eyebrow">{eyebrow}</div><h1 className="section-title mt-2 text-forest">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-ink/55">{body}</p></div>{action}</div>}
